name: RSpec Tests

on:
  push:
    branches:
      - '*'

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 1s
          --health-retries 5


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: 3.1.1

    - name: Cache Ruby Gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/*.gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --deployment --jobs 4 --retry 3

    - name: Setup Database
      env:
        RAILS_ENV: test
        DATABASE_NAME_TEST: myapp_test
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: 5432
        DATABASE_USER: postgres
      run: |
        bundle exec rails db:drop
        bundle exec rails db:test:prepare
        bundle exec rails db:seed

    - name: Determine Working Branch
      id: working_branch
      run: echo "BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')" >> $GITHUB_ENV

    - name: Run RSpec Tests
      run: |
          bundle exec rspec
